Bump dotnet to 8 LTS and get rid of 404 on index page.
jberlyn/kosync-dotnet pull request #5
Opened 2024-11-18 00:26 UTC by Fisiu

2025-02-19 09:39 UTC, jberlyn requested changes

2025-02-19 09:39 UTC, jberlyn commented on Dockerfile
> +EXPOSE 8080
Is there a reason we need to expose port 8080 here compared to the previous Dockerfile?

2025-02-19 22:27 UTC, Fisiu commented on Dockerfile
> +EXPOSE 8080
It's a common practice to expose port that application is listening to.
With `EXPOSE` in place, you can run container without specifying `-p` and port 8080 will be binded to same port on the host. And also, having specific port exposed, you know what port is even used by application.

Feel free to narrow down to tcp only:
`EXPOSE 8080/tcp`

2025-02-27 05:43 UTC, jberlyn approved these changes

2025-02-27 05:44 UTC, merged